### ISSUE TITLE
How do you stay motivated on personal projects once the interesting work is finished?

### ISSUE THREAD

**Issue by lukewestby** [iheanyi/ama#5]

**Comment by iheanyi** [comment]
Hmmm, this is a tough one. I think I am more motivated to work on improving personal projects if they have actual users. So if I know there's a way I could improve my personal project, I'm going to do it because my users are dependent on that personal project, you know? I think also, as I learn more and more about a framework/technology, it makes me want to go back and rewrite the project again, because I know I can do it better the second time around.
